=== 새로운 골 추가
==== 요청
operation::goal-controller-test/골_생성을_요청하면_새로운_골을_생성한다[snippets='http-request,request-headers,request-fields']
==== 응답
operation::goal-controller-test/골_생성을_요청하면_새로운_골을_생성한다[snippets='http-response,response-body']

=== 단일 골 정보 조회
==== 요청
operation::goal-controller-test/골_아이디로_조회하면_해당_골의_정보를_반환한다[snippets='http-request,path-parameters,request-headers']
==== 응답
operation::goal-controller-test/골_아이디로_조회하면_해당_골의_정보를_반환한다[snippets='http-response,response-body,response-fields']

=== 현재 로그인한 사용자가 참여한 현재 진행중인 모든 골 조회
==== 요청
operation::goal-controller-test/현재_로그인한_사용자가_참여한_현재_진행중인_모든_골을_조회한다[snippets='http-request,request-headers']
==== 응답
operation::goal-controller-test/현재_로그인한_사용자가_참여한_현재_진행중인_모든_골을_조회한다[snippets='http-response,response-body,response-fields']

=== 현재 로그인한 사용자가 참여한 종료된 모든 골 조회
==== 요청
operation::goal-controller-test/현재_로그인한_사용자가_참여한_종료된_모든_골을_조회한다[snippets='http-request,request-headers']
==== 응답
operation::goal-controller-test/현재_로그인한_사용자가_참여한_종료된_모든_골을_조회한다[snippets='http-response,response-body,response-fields']

=== 골 삭제
==== 요청
operation::goal-controller-test/요청한_아이디의_골을_삭제한다[snippets='http-request,path-parameters,request-headers']
==== 응답
operation::goal-controller-test/요청한_아이디의_골을_삭제한다[snippets='http-response']

=== 골 수정
==== 요청
operation::goal-controller-test/요청한_내용으로_골을_수정한다[snippets='http-request,path-parameters,request-headers']
==== 응답
operation::goal-controller-test/요청한_내용으로_골을_수정한다[snippets='http-response']
